name: Call a reusable workflow

on:
  workflow_dispatch:

jobs:
  # call-workflow:
  #   uses: sanketswani/dockerizeApp/.github/workflows/resuable_WF1_DockerImaging.yml@main
  #   with:
  #     firstInput: "Hello Sanket"
  #     APP_SUBMODULE: "test Module"
  #     ACR_ADDR: "Test ACR"
  # print-output:
  #   runs-on: ubuntu-latest
  #   needs: call-workflow
  #   steps:
  #     - run: echo ${{ needs.call-workflow.outputs.firstOutput }}
  job1:
    name: Modifiy repository files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: install pip and run shell
        run: |
          pip install yq
          ls -lr

      - name: Make script executable
        run: chmod +x edit_yaml.sh

      - name: Run edit_yaml.sh
        run: |
          FILE="testfile.yml"
          yq -i -y '.configmap.ABC = "v1.0.0"' $FILE
        shell: bash

      - name: Commit changes
        run: |
          git config --global user.name 'sanketswani'
          git config --global user.email 'sankeyswani@gmail.com'
          git add testfile.yml
          git commit -m "Update testfile.yml via GitHub Actions"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}