name: Call a reusable workflow

on:
  push:
    branches:
      - main

jobs:
  call-workflow:
    uses: dockerizeApp/.github/workflows/resuable_WF1_DockerImaging.yml@main
    with:
      firstInput: Hello World
  print-output:
    runs-on: ubuntu-latest
    needs: call-workflow
    steps:
      - run: echo ${{ needs.call-workflow.outputs.firstOutput }}
